INSERT INTO subscription_plans (code,
                                name,
                                description,
                                tier,
                                price_amount,
                                price_currency,
                                duration_days,
                                monthly_assessment_limit,
                                monthly_assessment_audio_seconds,
                                max_assessment_audio_seconds,
                                monthly_conversation_seconds,
                                max_conversation_session_seconds,
                                max_conversation_turns_per_session,
                                full_curriculum_access,
                                progress_analytics_enabled,
                                sample_answer_enabled,
                                status,
                                created_time,
                                modified_time)
VALUES ('FREE',
        'Gói Miễn Phí',
        'Trải nghiệm học tập miễn phí với các tính năng cơ bản.',
        'FREE',
        0.0000,
        'VND',
        9999,
        15,
        1800,
        120,
        1800,
        600,
        10,
        FALSE,
        FALSE,
        FALSE,
        'ACTIVE',
        NOW(),
        NULL),
       ('BASIC',
        'Gói Cơ Bản',
        'Học tập mở rộng với đầy đủ giáo trình và giới hạn vừa phải.',
        'BASIC',
        79000.0000,
        'VND',
        30,
        150,
        18000,
        180,
        18000,
        1200,
        25,
        TRUE,
        TRUE,
        TRUE,
        'ACTIVE',
        NOW(),
        NULL),
       ('PREMIUM',
        'Gói Cao Cấp',
        'Trải nghiệm tối đa, không giới hạn học tập và đầy đủ công cụ hỗ trợ gợi ý đáp án.',
        'PREMIUM',
        149000.0000,
        'VND',
        30,
        9999,
        999999,
        300,
        999999,
        3600,
        100,
        TRUE,
        TRUE,
        TRUE,
        'ACTIVE',
        NOW(),
        NULL);
