INSERT INTO subscription_plans (code,
                                description,
                                tier,
                                price_amount,
                                price_currency,
                                duration_days,
                                daily_speaking_question_evaluation_limit,
                                max_speaking_question_recording_seconds,
                                max_turns_per_ai_session,
                                daily_ai_session_start_limit,
                                max_ai_turn_speaking_seconds,
                                sample_answer_enabled,
                                status,
                                created_time)
VALUES ('FREE',
        'Trải nghiệm học tập miễn phí với các tính năng cơ bản.',
        'FREE',
        0.0000,
        'VND',
        NULL,
        1,
        45,
        5,
        1,
        20,
        FALSE,
        'ACTIVE',
        NOW()),
       ('BASIC',
        'Học tập mở rộng với đầy đủ giáo trình và giới hạn vừa phải.',
        'BASIC',
        99000.0000,
        'VND',
        30,
        3,
        60,
        10,
        2,
        30,
        TRUE,
        'ACTIVE',
        NOW()),
       ('PREMIUM',
        'Trải nghiệm học tập nâng cao với hạn mức cao và đầy đủ công cụ hỗ trợ gợi ý đáp án.',
        'PREMIUM',
        249000.0000,
        'VND',
        30,
        10,
        90,
        20,
        5,
        45,
        TRUE,
        'ACTIVE',
        NOW());