INSERT INTO daily_missions (id,
                            title,
                            description,
                            mission_type,
                            point,
                            created_time,
                            modified_time)
VALUES (1, 'Trò chuyện với AI',
        'Thực hiện trò chuyện với AI',
        'TALK_WITH_AI',
        5.0,
        NOW(),
        NULL),
       (2, 'Hoàn thành bài nói',
        'Hoàn thành 1 câu hỏi phát âm',
        'COMPLETE_SPEAKING_QUESTION_NODE',
        5.0,
        NOW(),
        NULL);
