-- Insert Roles
INSERT INTO roles (created_by,
                   created_time,
                   modified_by,
                   modified_time,
                   role_name,
                   description)
VALUES (0,
        NOW(),
        NULL,
        NULL,
        'ADMIN',
        ''),
       (0,
        NOW(),
        NULL,
        NULL,
        'STUDENT',
        ''),
       (0,
        NOW(),
        NULL,
        NULL,
        'TEACHER',
        '');