-- Insert Roles
INSERT INTO roles (created_by,
                   created_time,
                   modified_by,
                   modified_time,
                   role_name,
                   description)
VALUES ('system',
        NOW(),
        NULL,
        NULL,
        'ADMIN',
        ''),
       ('system',
        NOW(),
        NULL,
        NULL,
        'STUDENT',
        ''),
       ('system',
        NOW(),
        NULL,
        NULL,
        'TEACHER',
        '');