INSERT INTO users (created_by,
                   created_time,
                   username,
                   email,
                   hash_password,
                   account_type,
                   jlpt_level,
                   status)
VALUES (0,
        NOW(),
        'testuser',
        'test@example.com',
        '{bcrypt}$2a$10$mLvl6v0NmQ4f5cP6360qnueyzPYTyLizOJDyr7gL2DbAnnFzbK0mq',
        'CREDENTIALS',
        'N5',
        'ACTIVE');