-- Book cover image data
INSERT INTO files (id,
                   created_time,
                   object_key,
                   bucket_name,
                   original_name,
                   content_type,
                   size,
                   operation_type,
                   operation_status,
                   retry_count)
VALUES (11, NOW(), 'books/A1.jpeg', 'naho-public-bucket', 'A1.jpeg', 'image/jpeg', 197300, 'UPLOAD', 'COMPLETED', 0),
       (12, NOW(), 'books/A2.jpeg', 'naho-public-bucket', 'A2.jpeg', 'image/jpeg', 252500, 'UPLOAD', 'COMPLETED', 0),
       (13, NOW(), 'books/A2-2.jpeg', 'naho-public-bucket', 'A2-2.jpeg', 'image/jpeg', 214700, 'UPLOAD', 'COMPLETED',
        0),
       (14, NOW(), 'books/A2B1.jpeg', 'naho-public-bucket', 'A2B1.jpeg', 'image/jpeg', 238200, 'UPLOAD', 'COMPLETED',
        0),
       (15, NOW(), 'books/B1.jpeg', 'naho-public-bucket', 'B1.jpeg', 'image/jpeg', 128800, 'UPLOAD', 'COMPLETED', 0),
       (16, NOW(), 'books/B1-2.jpeg', 'naho-public-bucket', 'B1-2.jpeg', 'image/jpeg', 128200, 'UPLOAD', 'COMPLETED',
        0);

-- Book data
INSERT INTO books (id,
                   title,
                   `description`,
                   jlpt_level,
                   cefr_level,
                   order_index,
                   cover_image_file_id,
                   created_time,
                   modified_time)
VALUES (1,
        'Marugoto A1',
        'Giáo trình Marugoto trình độ A1 dành cho người mới bắt đầu học tiếng Nhật.',
        'N5',
        'A1',
        1.0,
        11,
        NOW(),
        NULL),
       (2,
        'Marugoto A2 (P1)',
        'Giáo trình Marugoto trình độ A2-1 dành cho người học ở trình độ sơ cấp.',
        'N4',
        'A2',
        2.0,
        12,
        NOW(),
        NULL),
       (3,
        'Marugoto A2 (P2)',
        'Giáo trình Marugoto trình độ A2-2 dành cho người học ở trình độ sơ cấp.',
        'N4',
        'A2',
        3.0,
        13,
        NOW(),
        NULL),
       (4,
        'Marugoto A2/B1',
        'Giáo trình Marugoto trình độ chuyển tiếp từ A2 lên B1.',
        'N3',
        'A2B1',
        4.0,
        14,
        NOW(),
        NULL),
       (5,
        'Marugoto B1 (P1)',
        'Giáo trình Marugoto trình độ B1-1 dành cho người học có khả năng giao tiếp độc lập.',
        'N3',
        'B1',
        5.0,
        15,
        NOW(),
        NULL),
       (6,
        'Marugoto B1 (P2)',
        'Giáo trình Marugoto trình độ B1-2 dành cho người học có khả năng giao tiếp độc lập.',
        'N3',
        'B1',
        6.0,
        16,
        NOW(),
        NULL);