-- Book cover image data
INSERT INTO files (id, created_time, modified_time, object_key, original_name, content_type, size, comment_id,
                   question_id, report_id)
VALUES (11, NOW(), NULL, 'books/A1.jpeg', 'A1.jpeg', 'image/jpeg', 197300, NULL, NULL, NULL),
       (12, NOW(), NULL, 'books/A2.jpeg', 'A2.jpeg', 'image/jpeg', 252500, NULL, NULL, NULL),
       (13, NOW(), NULL, 'books/A2-2.jpeg', 'A2-2.jpeg', 'image/jpeg', 214700, NULL, NULL, NULL),
       (14, NOW(), NULL, 'books/A2B1.jpeg', 'A2B1.jpeg', 'image/jpeg', 238200, NULL, NULL, NULL),
       (15, NOW(), NULL, 'books/B1.jpeg', 'B1.jpeg', 'image/jpeg', 128800, NULL, NULL, NULL),
       (16, NOW(), NULL, 'books/B1-2.jpeg', 'B1-2.jpeg', 'image/jpeg', 128200, NULL, NULL, NULL);

-- Book data
INSERT INTO books (title,
                   `description`,
                   jlpt_level,
                   cefr_level,
                   order_index,
                   cover_image_file_id,
                   created_time,
                   modified_time)
VALUES ('Marugoto A1',
        'Giáo trình Marugoto trình độ A1 dành cho người mới bắt đầu học tiếng Nhật.',
        'N5',
        'A1',
        1.0,
        11,
        NOW(),
        NULL),
       ('Marugoto A2-1',
        'Giáo trình Marugoto trình độ A2-1 dành cho người học ở trình độ sơ cấp.',
        'N4',
        'A2',
        2.0,
        12,
        NOW(),
        NULL),
       ('Marugoto A2-2',
        'Giáo trình Marugoto trình độ A2-2 dành cho người học ở trình độ sơ cấp.',
        'N4',
        'A2',
        2.0,
        13,
        NOW(),
        NULL),
       ('Marugoto A2/B1',
        'Giáo trình Marugoto trình độ chuyển tiếp từ A2 lên B1.',
        'N3',
        'A2B1',
        3.0,
        14,
        NOW(),
        NULL),
       ('Marugoto B1-1',
        'Giáo trình Marugoto trình độ B1-1 dành cho người học có khả năng giao tiếp độc lập.',
        'N3',
        'B1',
        4.0,
        15,
        NOW(),
        NULL),
       ('Marugoto B1-2',
        'Giáo trình Marugoto trình độ B1-2 dành cho người học có khả năng giao tiếp độc lập.',
        'N3',
        'B1',
        4.0,
        16,
        NOW(),
        NULL);