# -- SQL Migration File generated for Category, Topic, Question, Vocab and Grammar data
# -- Created for vuongtruc2004 (UserID = 1)
#
# -- Category: 日常生活 (Cuộc sống thường ngày)
# INSERT INTO category (id, created_time, modified_time, category_name) VALUES (1, NOW(), NULL, '日常生活 (Cuộc sống thường ngày)');
# -- Topic: 故郷・住んでいる町
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (1, NOW(), NULL, '故郷・住んでいる町', '住んでいる町', '故郷・住んでいる町', '住んでいる町', 'ACTIVE', 'N5', 1.0, NULL, 1, 1);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (1, NOW(), NULL, 'あなたが住んでいる町の地形や自然環境について説明してください。また、その町の好きなところも話してください。', 'あなたがすんでいるまちのちけいやしぜんかんきょうについてせつめいしてください。また、そのまちのすきなところもはなしてください。', 'Hãy giải thích về địa hình và môi trường tự nhiên của thành phố bạn đang sống. Ngoài ra, hãy nói về những điểm bạn thích ở thành phố đó.', 'Hãy giải thích về địa hình và môi trường tự nhiên của thành phố bạn đang sống. Ngoài ra, hãy nói về những điểm bạn thích ở thành phố đó.', 1.0, 'PUBLISHED', NULL, 1, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (1, NOW(), NULL, '地形: Địa hình', '地形: Terrain');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (2, NOW(), NULL, '自然環境: Môi trường tự nhiên', '自然環境: Natural environment');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (1, NOW(), NULL, '〜について (Về...)', '〜について (About...)', 'Diễn tả chủ đề hoặc nội dung cần giải thích, bàn luận.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (2, NOW(), NULL, '外国人の友達にあなたの故郷を紹介するとしたら、どんな場所や食べ物を紹介しますか。理由も含めて話してください。', 'がいこくじんのともだちにあなたのこきょうをしょうかいするとしたら、どんなばしょやたべものをしょうかいしますか。りゆうもふくめてはなしてください。', 'Nếu giới thiệu quê hương của bạn cho một người bạn nước ngoài, bạn sẽ giới thiệu địa điểm hoặc món ăn nào? Hãy nói kèm theo cả lý do.', 'Nếu giới thiệu quê hương của bạn cho một người bạn nước ngoài, bạn sẽ giới thiệu địa điểm hoặc món ăn nào? Hãy nói kèm theo cả lý do.', 2.0, 'PUBLISHED', NULL, 1, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (3, NOW(), NULL, '故郷: Quê hương', '故郷: Hometown');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (4, NOW(), NULL, '紹介: Giới thiệu', '紹介: Introduction');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (2, NOW(), NULL, '〜としたら (Nếu / Giả sử...)', '〜としたら (If / Supposing...)', 'Diễn tả một giả định về hành động hoặc trạng thái.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (3, NOW(), NULL, 'あなたの故郷は昔と比べてどのように変わりましたか。良くなった点と課題だと思う点を話してください。', 'あなたのこきょうはむかしとくらべてどのようにかわりましたか。よくたてんとかだいだとおもうてんをはなしてください。', 'Quê hương bạn đã thay đổi như thế nào so với ngày xưa? Hãy nêu những điểm tốt hơn và những vấn đề bạn nghĩ cần giải quyết.', 'Quê hương bạn đã thay đổi như thế nào so với ngày xưa? Hãy nêu những điểm tốt hơn và những vấn đề bạn nghĩ cần giải quyết.', 3.0, 'PUBLISHED', NULL, 1, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (5, NOW(), NULL, '比べる: So sánh', '比べる: Compare');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (6, NOW(), NULL, '課題: Vấn đề / Thử thách', '課題: Issue / Challenge');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (3, NOW(), NULL, '〜と比べて (So với...)', '〜と比べて (Compared to...)', 'Sử dụng để so sánh đối chiếu giữa hai sự vật, sự việc.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (4, NOW(), NULL, '将来も故郷に住みたいですか。それとも別の場所で暮らしたいですか。理由も説明してください。', 'しょうらいもこきょうにすみたいですか。それともべつのばしょでくらしたいですか。りゆうもせつめいしてください。', 'Trong tương lai bạn vẫn muốn sống ở quê hương chứ? Hay bạn muốn sinh sống ở một nơi khác? Hãy giải thích lý do.', 'Trong tương lai bạn vẫn muốn sống ở quê hương chứ? Hay bạn muốn sinh sống ở một nơi khác? Hãy giải thích lý do.', 4.0, 'PUBLISHED', NULL, 1, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (7, NOW(), NULL, '将来: Tương lai', '将来: Future');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (8, NOW(), NULL, '暮らす: Sinh sống', '暮らす: Live');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (4, NOW(), NULL, 'それとも (Hoặc là / Hay là...)', 'それとも (Or...)', 'Dùng để liên kết các câu hỏi lựa chọn.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (5, NOW(), NULL, 'あなたの町をもっと住みやすくするためには、どのような改善が必要だと思いますか。', 'あなたのまちをもっとすみやすくするためには、どのようなかいぜんがひつようだとおもいますか。', 'Để thành phố của bạn trở nên đáng sống hơn, bạn nghĩ cần có những cải thiện như thế nào?', 'Để thành phố của bạn trở nên đáng sống hơn, bạn nghĩ cần có những cải thiện như thế nào?', 5.0, 'PUBLISHED', NULL, 1, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (9, NOW(), NULL, '住みやすい: Dễ sống / Đáng sống', '住みやすい: Easy to live');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (10, NOW(), NULL, '改善: Cải thiện', '改善: Improvement');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (5, NOW(), NULL, '〜ために (Để / Nhằm mục đích...)', '〜ために (In order to...)', 'Diễn tả mục đích thực hiện hành động.');
# -- Topic: 毎日の生活習慣
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (2, NOW(), NULL, '毎日の生活習慣', '毎日の生活習慣', '毎日の生活習慣', '毎日の生活習慣', 'ACTIVE', 'N5', 2.0, NULL, 1, 1);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (6, NOW(), NULL, '毎日続けている習慣がありますか。それを続けている理由と効果を話してください。', 'まいにちつづけているしゅうかんがありますか。それをつづけているりゆうとこうかをはなしてください。', 'Bạn có thói quen nào duy trì hàng ngày không? Hãy nói về lý do duy trì và hiệu quả của nó.', 'Bạn có thói quen nào duy trì hàng ngày không? Hãy nói về lý do duy trì và hiệu quả của nó.', 1.0, 'PUBLISHED', NULL, 2, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (11, NOW(), NULL, '習慣: Thói quen', '習慣: Habit');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (12, NOW(), NULL, '効果: Hiệu quả', '効果: Effect');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (6, NOW(), NULL, '〜ている (Đang làm gì...)', '〜ている (Doing...)', 'Diễn tả hành động đang tiếp diễn hoặc thói quen.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (7, NOW(), NULL, '理想的な一日とはどのような一日だと思いますか。', 'りそうてきないちにちとはどのようないちにちだとおもいますか。', 'Theo bạn, một ngày lý tưởng là một ngày như thế nào?', 'Theo bạn, một ngày lý tưởng là một ngày như thế nào?', 2.0, 'PUBLISHED', NULL, 2, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (13, NOW(), NULL, '理想的: Lý tưởng', '理想的: Ideal');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (14, NOW(), NULL, '一日: Một ngày', '一日: One day');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (7, NOW(), NULL, '〜とは (Cái gọi là...)', '〜とは (Means...)', 'Dùng để định nghĩa hoặc giải thích thuật ngữ.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (8, NOW(), NULL, '休日と平日の生活はどのように違いますか。', 'きゅうじつとへいじつのせいかつはどのようにちがいますか。', 'Cuộc sống của bạn vào ngày nghỉ và ngày thường khác nhau như thế nào?', 'Cuộc sống của bạn vào ngày nghỉ và ngày thường khác nhau như thế nào?', 3.0, 'PUBLISHED', NULL, 2, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (15, NOW(), NULL, '休日: Ngày nghỉ', '休日: Holiday');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (16, NOW(), NULL, '平日: Ngày thường', '平日: Weekday');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (8, NOW(), NULL, '〜と〜 (Và...)', '〜と〜 (And...)', 'Nối hai danh từ.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (9, NOW(), NULL, '最近、生活習慣を改善しようと思ったことがありますか。その理由も話してください。', 'さいきん、せいかつしゅうかんをかいぜんしようとおもったことがありますか。そのりゆうもはなしてください。', 'Gần đây bạn có từng nghĩ đến việc cải thiện thói quen sinh hoạt không? Hãy nói về lý do của việc đó.', 'Gần đây bạn có từng nghĩ đến việc cải thiện thói quen sinh hoạt không? Hãy nói về lý do của việc đó.', 4.0, 'PUBLISHED', NULL, 2, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (17, NOW(), NULL, '生活習慣: Thói quen sinh hoạt', '生活習慣: Lifestyle habit');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (18, NOW(), NULL, '最近: Gần đây', '最近: Recently');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (9, NOW(), NULL, '〜ようと思う (Định làm gì...)', '〜ようと思う (Intend to...)', 'Diễn tả quyết định hoặc dự định.');
# -- Category: 観光・紹介 (Du lịch & Giới thiệu)
# INSERT INTO category (id, created_time, modified_time, category_name) VALUES (2, NOW(), NULL, '観光・紹介 (Du lịch & Giới thiệu)');
# -- Topic: 一日観光プラン
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (3, NOW(), NULL, '一日観光プラン', '一日観光プラン', '一日観光プラン', '一日観光プラン', 'ACTIVE', 'N4', 3.0, NULL, 1, 2);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (10, NOW(), NULL, '【ハノイ】に行く友達がいます。泊まる時間は１日だけです。その１日にできる面白いことを紹介してください。', '【ハノイ】にいくともだちがいます。とまるじかんは１にちだけです。その１にちにできるおもしろいことをしょうかいしてください。', 'Bạn có một người bạn chuẩn bị đi Hà Nội. Thời gian ở lại chỉ có 1 ngày. Hãy giới thiệu những hoạt động thú vị có thể làm trong ngày đó.', 'Bạn có một người bạn chuẩn bị đi Hà Nội. Thời gian ở lại chỉ có 1 ngày. Hãy giới thiệu những hoạt động thú vị có thể làm trong ngày đó.', 1.0, 'PUBLISHED', NULL, 3, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (19, NOW(), NULL, '泊まる: Trú lại / Ở lại', '泊まる: Stay overnight');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (20, NOW(), NULL, '面白い: Thú vị', '面白い: Interesting');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (10, NOW(), NULL, '〜だけ (Chỉ...)', '〜だけ (Only...)', 'Biểu thị giới hạn phạm vi, mức độ.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (11, NOW(), NULL, 'あなたの町に１日しか滞在できない観光客がいます。どのようなスケジュールを提案しますか。', 'あなたのまちに１にちしかたいざいできないかんこうきゃくがいます。どのようなスケジュールをていあんしますか。', 'Có một du khách chỉ có thể lưu lại thành phố của bạn trong 1 ngày. Bạn sẽ đề xuất lịch trình như thế nào?', 'Có một du khách chỉ có thể lưu lại thành phố của bạn trong 1 ngày. Bạn sẽ đề xuất lịch trình như thế nào?', 2.0, 'PUBLISHED', NULL, 3, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (21, NOW(), NULL, '滞在: Tạm trú / Lưu lại', '滞在: Stay');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (22, NOW(), NULL, '提案: Đề xuất / Gợi ý', '提案: Proposal');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (11, NOW(), NULL, '〜しか〜ない (Chỉ có...)', '〜しか〜ない (Only...)', 'Nhấn mạnh mức độ hạn chế (đi với phủ định).');
# -- Topic: ベトナム文化紹介
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (4, NOW(), NULL, 'ベトナム文化紹介', 'ベトナム文化紹介', 'ベトナム文化紹介', 'ベトナム文化紹介', 'ACTIVE', 'N4', 4.0, NULL, 1, 2);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (12, NOW(), NULL, '日本から友達がベトナムに遊びに来ます。ぜひ体験してほしいことを紹介してください。', 'にほんからともだちがベトナムにあそびにきます。ぜひたいけんしてほしいことをしょうかいしてください。', 'Một người bạn từ Nhật Bản đến Việt Nam chơi. Hãy giới thiệu những điều bạn thực sự muốn họ trải nghiệm.', 'Một người bạn từ Nhật Bản đến Việt Nam chơi. Hãy giới thiệu những điều bạn thực sự muốn họ trải nghiệm.', 1.0, 'PUBLISHED', NULL, 4, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (23, NOW(), NULL, '体験: Trải nghiệm', '体験: Experience');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (24, NOW(), NULL, '遊びに来る: Đến chơi', '遊びに来る: Come to visit');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (12, NOW(), NULL, '〜てほしい (Muốn ai đó làm...)', '〜てほしい (Want someone to do...)', 'Diễn tả mong muốn của người nói với hành động đối phương.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (13, NOW(), NULL, '外国人にベトナム文化を紹介するとしたら、何を紹介しますか。', 'がいこくじんにベトナムぶんかでしょうかいするとしたら、なにでしょうかいしますか。', 'Nếu giới thiệu văn hóa Việt Nam cho người nước ngoài, bạn sẽ giới thiệu điều gì?', 'Nếu giới thiệu văn hóa Việt Nam cho người nước ngoài, bạn sẽ giới thiệu điều gì?', 2.0, 'PUBLISHED', NULL, 4, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (25, NOW(), NULL, '外国人: Người nước ngoài', '外国人: Foreigner');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (26, NOW(), NULL, '文化: Văn hóa', '文化: Culture');
# -- Topic: おすすめの場所・店
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (5, NOW(), NULL, 'おすすめの場所・店', '店', 'おすすめの場所・店', '店', 'ACTIVE', 'N4', 5.0, NULL, 1, 2);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (14, NOW(), NULL, 'あなたの好きなレストランを紹介してください。', 'あなたのすきなレストランをしょうかいしてください。', 'Hãy giới thiệu nhà hàng yêu thích của bạn.', 'Hãy giới thiệu nhà hàng yêu thích của bạn.', 1.0, 'PUBLISHED', NULL, 5, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (27, NOW(), NULL, 'レストラン: Nhà hàng', 'レストラン: Restaurant');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (28, NOW(), NULL, '好き: Thích', '好き: Like');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (13, NOW(), NULL, '〜てください (Hãy...)', '〜てください (Please...)', 'Dùng để đưa ra yêu cầu lịch sự hoặc hướng dẫn.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (15, NOW(), NULL, '友達におすすめしたいカフェについて話してください。', 'ともだちにおすすめしたいカフェについてはなしてください。', 'Hãy nói về một quán cà phê mà bạn muốn gợi ý cho bạn bè.', 'Hãy nói về một quán cà phê mà bạn muốn gợi ý cho bạn bè.', 2.0, 'PUBLISHED', NULL, 5, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (29, NOW(), NULL, 'おすすめ: Gợi ý / Đề xuất', 'おすすめ: Recommendation');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (30, NOW(), NULL, 'カフェ: Quán cà phê', 'カフェ: Cafe');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (14, NOW(), NULL, '〜たい (Muốn...)', '〜たい (Want to...)', 'Diễn tả nguyện vọng bản thân.');
# -- Category: 趣味・価値観 (Sở thích & Giá trị sống)
# INSERT INTO category (id, created_time, modified_time, category_name) VALUES (3, NOW(), NULL, '趣味・価値観 (Sở thích & Giá trị sống)');
# -- Topic: 本・映画
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (6, NOW(), NULL, '本・映画', '映画', '本・映画', '映画', 'ACTIVE', 'N3', 6.0, NULL, 1, 3);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (16, NOW(), NULL, '一番好きな本を教えてください。理由も説明してください。', 'いちばんすきなほんをおしえてください。りゆうもせつめいしてください。', 'Hãy cho biết cuốn sách bạn thích nhất. Hãy giải thích cả lý do.', 'Hãy cho biết cuốn sách bạn thích nhất. Hãy giải thích cả lý do.', 1.0, 'PUBLISHED', NULL, 6, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (31, NOW(), NULL, '本: Sách', '本: Book');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (32, NOW(), NULL, '一番: Nhất', '一番: Most / Number one');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (17, NOW(), NULL, '今まで見た映画の中で一番印象に残っている作品について話してください。', 'いままでみたえいがのなかでいちばんいんしょうにのこっているさくひんについてはなしてください。', 'Trong các bộ phim đã xem từ trước đến nay, hãy nói về tác phẩm để lại ấn tượng sâu sắc nhất cho bạn.', 'Trong các bộ phim đã xem từ trước đến nay, hãy nói về tác phẩm để lại ấn tượng sâu sắc nhất cho bạn.', 2.0, 'PUBLISHED', NULL, 6, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (33, NOW(), NULL, '印象: Ấn tượng', '印象: Impression');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (34, NOW(), NULL, '作品: Tác phẩm', '作品: Work / Piece');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (15, NOW(), NULL, '〜の中で (Trong số...)', '〜の中で (Among...)', 'Chọn lọc từ một nhóm.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (18, NOW(), NULL, 'もし一冊だけ本を友達にすすめるなら、どんな本を選びますか。', 'もしいっさつだけほんをともだちにすすめるなら、どんなほんをえらびますか。', 'Nếu chỉ đề xuất một cuốn sách duy nhất cho bạn bè, bạn sẽ chọn cuốn sách nào?', 'Nếu chỉ đề xuất một cuốn sách duy nhất cho bạn bè, bạn sẽ chọn cuốn sách nào?', 3.0, 'PUBLISHED', NULL, 6, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (35, NOW(), NULL, '勧める: Khuyên dùng / Gợi ý', '勧める: Recommend');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (36, NOW(), NULL, '選ぶ: Chọn', '選ぶ: Choose');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (16, NOW(), NULL, 'もし (Nếu...)', 'もし (If...)', 'Nhấn mạnh giả định.');
# -- Topic: 好きな言葉
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (7, NOW(), NULL, '好きな言葉', '好きな言葉', '好きな言葉', '好きな言葉', 'ACTIVE', 'N3', 7.0, NULL, 1, 3);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (19, NOW(), NULL, '一番好きな日本語の言葉を教えてください。理由も説明してください。', 'いちばんすきなにほんごのことばをおしえてください。りゆうもせつめいしてください。', 'Hãy cho biết từ tiếng Nhật bạn thích nhất. Giải thích lý do tại sao.', 'Hãy cho biết từ tiếng Nhật bạn thích nhất. Giải thích lý do tại sao.', 1.0, 'PUBLISHED', NULL, 7, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (37, NOW(), NULL, '言葉: Từ ngữ', '言葉: Word / Language');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (38, NOW(), NULL, '日本語: Tiếng Nhật', '日本語: Japanese');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (17, NOW(), NULL, '〜を〜 (Tác động vào tân ngữ...)', '〜を〜 (Object marker...)', 'Trợ từ chỉ tân ngữ.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (20, NOW(), NULL, 'あなたにとって大切な言葉を一つ紹介してください。その理由も話してください。', 'あなたにとってたいせつなことばをひとつしょうかいしてください。そのりゆうもはなしてください。', 'Hãy giới thiệu một câu nói/từ ngữ quan trọng đối với bạn. Hãy nói cả lý do.', 'Hãy giới thiệu một câu nói/từ ngữ quan trọng đối với bạn. Hãy nói cả lý do.', 2.0, 'PUBLISHED', NULL, 7, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (39, NOW(), NULL, '大切: Quan trọng', '大切: Important');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (40, NOW(), NULL, '一つ: Một cái', '一つ: One');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (18, NOW(), NULL, '〜にとって (Đối với...)', '〜にとって (To/For...)', 'Đưa ra đánh giá dưới góc nhìn của đối tượng.');
# -- Topic: 尊敬する人
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (8, NOW(), NULL, '尊敬する人', '尊敬する人', '尊敬する人', '尊敬する人', 'ACTIVE', 'N3', 8.0, NULL, 1, 3);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (21, NOW(), NULL, 'あなたが尊敬している人について紹介してください。その人から学んだことは何ですか。', 'あなたがそんけいしているひとについてしょうかいしてください。そのひとからまなんだことはなんですか。', 'Hãy giới thiệu về người mà bạn kính trọng. Bạn đã học được điều gì từ người đó?', 'Hãy giới thiệu về người mà bạn kính trọng. Bạn đã học được điều gì từ người đó?', 1.0, 'PUBLISHED', NULL, 8, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (41, NOW(), NULL, '尊敬: Kính trọng', '尊敬: Respect');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (42, NOW(), NULL, '学ぶ: Học hỏi', '学ぶ: Learn');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (19, NOW(), NULL, '〜から (Từ...)', '〜から (From...)', 'Chỉ nguồn gốc, điểm xuất phát.');
# -- Topic: 人生観
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (9, NOW(), NULL, '人生観', '人生観', '人生観', '人生観', 'ACTIVE', 'N3', 9.0, NULL, 1, 3);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (22, NOW(), NULL, '人生で一番大切だと思うことは何ですか。理由も説明してください。', 'じんせいでいちばんたいせつだとおもうことはなんですか。りゆうもせつめいしてください。', 'Điều bạn nghĩ là quan trọng nhất trong cuộc sống là gì? Hãy giải thích lý do.', 'Điều bạn nghĩ là quan trọng nhất trong cuộc sống là gì? Hãy giải thích lý do.', 1.0, 'PUBLISHED', NULL, 9, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (43, NOW(), NULL, '人生: Cuộc đời', '人生: Life');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (44, NOW(), NULL, '思う: Nghĩ rằng', '思う: Think');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (20, NOW(), NULL, '〜と思う (Nghĩ rằng...)', '〜と思う (Think that...)', 'Nêu quan điểm bản thân.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (23, NOW(), NULL, '幸せな人生とはどのような人生だと思いますか。', 'しあわせなじんせとはどのようなじんせいだとおおいますか。', 'Theo bạn, một cuộc đời hạnh phúc là một cuộc đời như thế nào?', 'Theo bạn, một cuộc đời hạnh phúc là một cuộc đời như thế nào?', 2.0, 'PUBLISHED', NULL, 9, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (45, NOW(), NULL, '幸せ: Hạnh phúc', '幸せ: Happiness');
# -- Category: 人間関係 (Các mối quan hệ)
# INSERT INTO category (id, created_time, modified_time, category_name) VALUES (4, NOW(), NULL, '人間関係 (Các mối quan hệ)');
# -- Topic: 友達
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (10, NOW(), NULL, '友達', '友達', '友達', '友達', 'ACTIVE', 'N3', 10.0, NULL, 1, 4);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (24, NOW(), NULL, '信頼できる友達とはどのような人だと思いますか。', 'しんらいできるともだちとはどのようなひとだとおもいますか。', 'Theo bạn, một người bạn đáng tin cậy là người như thế nào?', 'Theo bạn, một người bạn đáng tin cậy là người như thế nào?', 1.0, 'PUBLISHED', NULL, 10, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (46, NOW(), NULL, '信頼: Tin cậy', '信頼: Trust');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (47, NOW(), NULL, '友達: Bạn bè', '友達: Friend');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (21, NOW(), NULL, '〜ができる (Có thể...)', '〜ができる (Can...)', 'Thể khả năng của động từ.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (25, NOW(), NULL, '今まで友達を助けた経験について話してください。', 'いままでともだちをたすけたけいけんについてはなしてください。', 'Hãy nói về trải nghiệm giúp đỡ bạn bè từ trước đến nay của bạn.', 'Hãy nói về trải nghiệm giúp đỡ bạn bè từ trước đến nay của bạn.', 2.0, 'PUBLISHED', NULL, 10, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (48, NOW(), NULL, '助ける: Giúp đỡ', '助ける: Help / Save');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (49, NOW(), NULL, '経験: Kinh nghiệm', '経験: Experience');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (22, NOW(), NULL, '〜たことがある (Đã từng...)', '〜たことがある (Have experience...)', 'Diễn tả kinh nghiệm đã từng làm.');
# -- Topic: 悩み相談
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (11, NOW(), NULL, '悩み相談', '悩み相談', '悩み相談', '悩み相談', 'ACTIVE', 'N3', 11.0, NULL, 1, 4);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (26, NOW(), NULL, '人から悩みをシェアしてもらったことがありますか。そのとき、あなたの気持ちはどうでしたか。', 'ひとからなやみをシェアしてもらったことがありますか。そのとき、あなたのきもちはどうでしたか。', 'Bạn đã từng được ai đó chia sẻ khó khăn/nỗi lòng chưa? Lúc đó, cảm xúc của bạn như thế nào?', 'Bạn đã từng được ai đó chia sẻ khó khăn/nỗi lòng chưa? Lúc đó, cảm xúc của bạn như thế nào?', 1.0, 'PUBLISHED', NULL, 11, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (50, NOW(), NULL, '悩み: Nỗi lo lắng', '悩み: Worry');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (51, NOW(), NULL, '気持ち: Cảm xúc', '気持ち: Feeling');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (23, NOW(), NULL, '〜てもらう (Được ai làm giúp...)', '〜てもらう (Have someone do...)', 'Nhận hành động giúp đỡ.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (27, NOW(), NULL, 'あなたは友達の相談に乗ることが好きですか。理由も話してください。', 'あなたはともだちのそうだんにのることがすきですか。りゆうもはなしてください。', 'Bạn có thích lắng nghe/chia sẻ lời khuyên cho bạn bè không? Hãy nêu lý do.', 'Bạn có thích lắng nghe/chia sẻ lời khuyên cho bạn bè không? Hãy nêu lý do.', 2.0, 'PUBLISHED', NULL, 11, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (52, NOW(), NULL, '相談に乗る: Lắng nghe/Cho lời khuyên', '相談に乗る: Give advice');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (24, NOW(), NULL, '〜こと (Việc...)', '〜こと (Doing...)', 'Danh từ hóa hành động.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (28, NOW(), NULL, '悩みがあるとき、誰に相談することが多いですか。', 'なやみがあるとき、だれにそうだんすることがおおいですか。', 'Khi gặp khó khăn hay lo lắng, bạn thường tâm sự/tư vấn với ai?', 'Khi gặp khó khăn hay lo lắng, bạn thường tâm sự/tư vấn với ai?', 3.0, 'PUBLISHED', NULL, 11, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (53, NOW(), NULL, '相談: Tư vấn', '相談: Consultation');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (54, NOW(), NULL, '多い: Nhiều', '多い: Many');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (25, NOW(), NULL, '〜とき (Khi/Lúc...)', '〜とき (When...)', 'Chỉ thời điểm xảy ra hành động.');
# -- Topic: 励まし・サポート
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (12, NOW(), NULL, '励まし・サポート', 'サポート', '励まし・サポート', 'サポート', 'ACTIVE', 'N3', 12.0, NULL, 1, 4);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (29, NOW(), NULL, '友達が落ち込んでいるとき、どのように励ましますか。', 'ともだちがおちこんでいるとき、どのようにはげましますか。', 'Khi bạn bè đang buồn bã/nản lòng, bạn khích lệ họ bằng cách nào?', 'Khi bạn bè đang buồn bã/nản lòng, bạn khích lệ họ bằng cách nào?', 1.0, 'PUBLISHED', NULL, 12, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (55, NOW(), NULL, '落ち込む: Buồn bã', '落ち込む: Down / Depressed');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (56, NOW(), NULL, '励ます: Khích lệ', '励ます: Encourage');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (26, NOW(), NULL, 'どのように (Làm sao/Như thế nào)', 'どのように (How)', 'Từ hỏi về phương thức.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (30, NOW(), NULL, '人から感謝された経験について話してください。', 'ひとからかんしゃされたけいけんについてはなしてください。', 'Hãy kể về trải nghiệm bạn được người khác cảm ơn.', 'Hãy kể về trải nghiệm bạn được người khác cảm ơn.', 2.0, 'PUBLISHED', NULL, 12, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (57, NOW(), NULL, '感謝: Cảm ơn', '感謝: Gratitude');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (27, NOW(), NULL, '〜される (Bị / Được...)', '〜される (Passive voice)', 'Thể bị động.');
# -- Topic: 人間関係の考え方
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (13, NOW(), NULL, '人間関係の考え方', '人間関係の考え方', '人間関係の考え方', '人間関係の考え方', 'ACTIVE', 'N3', 13.0, NULL, 1, 4);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (31, NOW(), NULL, '人間関係で大切だと思うことは何ですか。', 'にんげんかんけいでたいせつだとおもうことはなんですか。', 'Bạn nghĩ điều gì là quan trọng nhất trong mối quan hệ giữa con người với nhau?', 'Bạn nghĩ điều gì là quan trọng nhất trong mối quan hệ giữa con người với nhau?', 1.0, 'PUBLISHED', NULL, 13, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (58, NOW(), NULL, '人間関係: Mối quan hệ', '人間関係: Relationship');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (28, NOW(), NULL, '〜で (Trong / Tại...)', '〜で (In / At...)', 'Chỉ phạm vi hoặc địa điểm.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (32, NOW(), NULL, '良い人間関係を築くために必要なことは何ですか。', 'よいいにんげんかんけいをきずくためにひつようなことはなんですか。', 'Để xây dựng mối quan hệ tốt đẹp giữa con người, điều cần thiết là gì?', 'Để xây dựng mối quan hệ tốt đẹp giữa con người, điều cần thiết là gì?', 2.0, 'PUBLISHED', NULL, 13, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (59, NOW(), NULL, '築く: Xây dựng', '築く: Build');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (60, NOW(), NULL, '必要: Cần thiết', '必要: Necessary');
# -- Category: コミュニケーション (Giao tiếp)
# INSERT INTO category (id, created_time, modified_time, category_name) VALUES (5, NOW(), NULL, 'コミュニケーション (Giao tiếp)');
# -- Topic: 謝る
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (14, NOW(), NULL, '謝る', '謝る', '謝る', '謝る', 'ACTIVE', 'N3', 14.0, NULL, 1, 5);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (33, NOW(), NULL, 'あなたは人に「ごめんなさい」と言うとき、直接言いますか。それともメッセージで伝えますか。どうしてですか。', 'あなたはひとに「ごめんなさい」というとき、ちょくせついいますか。それともメッセージでつたえますか。どうしてですか。', 'Khi nói lời xin lỗi với người khác, bạn nói trực tiếp hay truyền đạt qua tin nhắn? Tại sao?', 'Khi nói lời xin lỗi với người khác, bạn nói trực tiếp hay truyền đạt qua tin nhắn? Tại sao?', 1.0, 'PUBLISHED', NULL, 14, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (61, NOW(), NULL, '直接: Trực tiếp', '直接: Directly');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (62, NOW(), NULL, 'メッセージ: Tin nhắn', 'メッセージ: Message');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (34, NOW(), NULL, '今までで一番印象に残っている謝罪の経験について話してください。', 'いままででいちばんいんしょうにのこっているしゃざいのけいけんについてはなしてください。', 'Hãy kể về trải nghiệm xin lỗi/tạ lỗi để lại ấn tượng sâu sắc nhất cho bạn từ trước đến nay.', 'Hãy kể về trải nghiệm xin lỗi/tạ lỗi để lại ấn tượng sâu sắc nhất cho bạn từ trước đến nay.', 2.0, 'PUBLISHED', NULL, 14, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (63, NOW(), NULL, '謝罪: Tạ lỗi', '謝罪: Apology');
# -- Topic: 感謝する
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (15, NOW(), NULL, '感謝する', '感謝する', '感謝する', '感謝する', 'ACTIVE', 'N3', 15.0, NULL, 1, 5);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (35, NOW(), NULL, '人に感謝を伝えるとき、どのような方法を使いますか。', 'ひとにかんしゃをつたえるとき、どのようなほうほうをつかいますか。', 'Khi bày tỏ sự biết ơn với ai đó, bạn sử dụng phương thức như thế nào?', 'Khi bày tỏ sự biết ơn với ai đó, bạn sử dụng phương thức như thế nào?', 1.0, 'PUBLISHED', NULL, 15, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (64, NOW(), NULL, '方法: Phương pháp', '方法: Method');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (29, NOW(), NULL, 'どのような (Như thế nào...)', 'どのような (What kind of...)', 'Hỏi về tính chất hoặc phương thức.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (36, NOW(), NULL, '感謝の気持ちを伝えてうれしかった経験がありますか。', 'かんしゃのきもちをつたえてうれしかったけいけんがありますか。', 'Bạn có trải nghiệm nào mà khi truyền đạt lòng biết ơn làm bạn cảm thấy vui sướng không?', 'Bạn có trải nghiệm nào mà khi truyền đạt lòng biết ơn làm bạn cảm thấy vui sướng không?', 2.0, 'PUBLISHED', NULL, 15, 1);
# -- Topic: SNSと会話
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (16, NOW(), NULL, 'SNSと会話', 'SNSと会話', 'SNSと会話', 'SNSと会話', 'ACTIVE', 'N3', 16.0, NULL, 1, 5);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (37, NOW(), NULL, 'SNSで伝えることと直接話すことにはどんな違いがあると思いますか。', 'エスエヌエスでつたえることとちょくせつはなすことにはどんなちがいがあるとおもいますか。', 'Bạn nghĩ truyền đạt qua mạng xã hội và nói chuyện trực tiếp có những điểm khác biệt như thế nào?', 'Bạn nghĩ truyền đạt qua mạng xã hội và nói chuyện trực tiếp có những điểm khác biệt như thế nào?', 1.0, 'PUBLISHED', NULL, 16, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (65, NOW(), NULL, '違い: Khác biệt', '違い: Difference');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (66, NOW(), NULL, 'SNS: Mạng xã hội', 'SNS: Social network');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (30, NOW(), NULL, '〜ことと〜こと (Việc... và việc...)', '〜ことと〜こと (Doing A and doing B...)', 'So sánh hai hành động hoặc danh từ hóa sự việc.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (38, NOW(), NULL, 'オンラインのコミュニケーションについてどう思いますか。', 'オンラインのコミュニケーションについてどうおもいますか。', 'Bạn nghĩ gì về giao tiếp trực tuyến?', 'Bạn nghĩ gì về giao tiếp trực tuyến?', 2.0, 'PUBLISHED', NULL, 16, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (67, NOW(), NULL, 'コミュニケーション: Giao tiếp', 'コミュニケーション: Communication');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (68, NOW(), NULL, 'オンライン: Trực tuyến', 'オンライン: Online');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (31, NOW(), NULL, '〜についてどう思う (Nghĩ gì về...)', '〜についてどう思う (What do you think about...)', 'Hỏi ý kiến của đối phương về một vấn đề.');
# -- Topic: けんかと仲直り
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (17, NOW(), NULL, 'けんかと仲直り', 'けんかと仲直り', 'けんかと仲直り', 'けんかと仲直り', 'ACTIVE', 'N3', 17.0, NULL, 1, 5);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (39, NOW(), NULL, '友達とけんかしたとき、どのように仲直りしますか。', 'ともだちとけんかしたとき、どのようになかなおりしますか。', 'Khi cãi vã với bạn bè, bạn thường làm hòa bằng cách nào?', 'Khi cãi vã với bạn bè, bạn thường làm hòa bằng cách nào?', 1.0, 'PUBLISHED', NULL, 17, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (69, NOW(), NULL, 'けんか: Cãi nhau', 'けんか: Quarrel');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (70, NOW(), NULL, '仲直り: Làm hòa', '仲直り: Reconciliation');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (32, NOW(), NULL, '〜したとき (Khi đã làm...)', '〜したとき (When...)', 'Thời điểm hành động trước đó đã xảy ra.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (40, NOW(), NULL, '意見が合わない人とどのように接しますか。', 'いけんがあわないひととどのようにせっしますか。', 'Bạn ứng xử thế nào đối với những người có ý kiến bất đồng?', 'Bạn ứng xử thế nào đối với những người có ý kiến bất đồng?', 2.0, 'PUBLISHED', NULL, 17, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (71, NOW(), NULL, '意見: Ý kiến', '意見: Opinion');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (72, NOW(), NULL, '接する: Ứng xử', '接する: Interact');
# -- Category: 社会活動 (Hoạt động xã hội)
# INSERT INTO category (id, created_time, modified_time, category_name) VALUES (6, NOW(), NULL, '社会活動 (Hoạt động xã hội)');
# -- Topic: ボランティア経験
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (18, NOW(), NULL, 'ボランティア経験', 'ボランティア経験', 'ボランティア経験', 'ボランティア経験', 'ACTIVE', 'N2', 18.0, NULL, 1, 6);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (41, NOW(), NULL, '今までどんなボランティア活動に参加しましたか。参加して感じたこと、考えたことを話してください。', 'いままでどんなボランティアかつどうにさんかしましたか。さんかしてかんじたこと、かんがえたことをはなしてください。', 'Từ trước đến nay bạn đã tham gia hoạt động tình nguyện nào? Hãy nói về những cảm nhận và suy nghĩ của bạn khi tham gia.', 'Từ trước đến nay bạn đã tham gia hoạt động tình nguyện nào? Hãy nói về những cảm nhận và suy nghĩ của bạn khi tham gia.', 1.0, 'PUBLISHED', NULL, 18, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (73, NOW(), NULL, 'ボランティア: Tình nguyện', 'ボランティア: Volunteer');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (74, NOW(), NULL, '活動: Hoạt động', '活動: Activity');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (33, NOW(), NULL, '〜て (Làm... rồi...)', '〜て (And then...)', 'Liên kết các hành động theo thứ tự thời gian.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (42, NOW(), NULL, 'ボランティア活動に参加しようと思ったきっかけは何ですか。', 'ボランティアかつどうにさんかしようとおもったきっかけはなんですか。', 'Động lực hay lý do khơi nguồn việc bạn quyết định tham gia hoạt động tình nguyện là gì?', 'Động lực hay lý do khơi nguồn việc bạn quyết định tham gia hoạt động tình nguyện là gì?', 2.0, 'PUBLISHED', NULL, 18, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (75, NOW(), NULL, 'きっかけ: Động cơ', 'きっかけ: Trigger');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (76, NOW(), NULL, '参加: Tham gia', '参加: Participate');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (43, NOW(), NULL, 'ボランティア活動を通して学んだことはありますか。活動を通して成長したと思うことを話してください。', 'ボランティアかつどうをとおしてまなんだことはありますか。かつどうをとおしてせいちょうしたとおもうことをはなしてください。', 'Bạn có học được điều gì thông qua hoạt động tình nguyện không? Hãy nói về điểm mà bạn nghĩ bản thân đã trưởng thành qua hoạt động đó.', 'Bạn có học được điều gì thông qua hoạt động tình nguyện không? Hãy nói về điểm mà bạn nghĩ bản thân đã trưởng thành qua hoạt động đó.', 3.0, 'PUBLISHED', NULL, 18, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (77, NOW(), NULL, '通して: Thông qua', '通して: Through');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (78, NOW(), NULL, '成長: Trưởng thành', '成長: Growth');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (34, NOW(), NULL, '〜を通して (Thông qua...)', '〜を通して (Through...)', 'Chỉ phương tiện trung gian.');
# -- Topic: 社会貢献
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (19, NOW(), NULL, '社会貢献', '社会貢献', '社会貢献', '社会貢献', 'ACTIVE', 'N2', 19.0, NULL, 1, 6);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (44, NOW(), NULL, '地域社会のために自分ができることは何だと思いますか。', 'ちいきしゃかいのためにじぶんができることはなんだとおもいますか。', 'Bạn nghĩ bản thân có thể làm gì để đóng góp cho cộng đồng địa phương?', 'Bạn nghĩ bản thân có thể làm gì để đóng góp cho cộng đồng địa phương?', 1.0, 'PUBLISHED', NULL, 19, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (79, NOW(), NULL, '地域社会: Cộng đồng địa phương', '地域社会: Local community');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (80, NOW(), NULL, '貢献: Cống hiến', '貢献: Contribute');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (35, NOW(), NULL, '〜のために (Vì lợi ích...)', '〜のために (For...)', 'Diễn tả mục tiêu hành động hướng đến đối tượng khác.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (45, NOW(), NULL, '大学生はボランティア活動に参加するべきだと思いますか。', 'だいがくせいはボランティアかつどうにさんかするべきだとおもいますか。', 'Bạn có nghĩ sinh viên đại học nên tham gia vào các hoạt động tình nguyện không?', 'Bạn có nghĩ sinh viên đại học nên tham gia vào các hoạt động tình nguyện không?', 2.0, 'PUBLISHED', NULL, 19, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (81, NOW(), NULL, '大学生: Sinh viên', '大学生: Student');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (82, NOW(), NULL, '当然: Đương nhiên', '当然: Naturally');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (36, NOW(), NULL, '〜べきだ (Nên / Phải...)', '〜べきだ (Should...)', 'Diễn tả bổn phận hoặc việc nên làm.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (46, NOW(), NULL, '将来、社会にどのように貢献したいですか。', 'しょうらい、しゃかいにどのようにこうけんしたいですか。', 'Trong tương lai, bạn muốn cống hiến cho xã hội bằng cách nào?', 'Trong tương lai, bạn muốn cống hiến cho xã hội bằng cách nào?', 3.0, 'PUBLISHED', NULL, 19, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (83, NOW(), NULL, '社会: Xã hội', '社会: Society');
# -- Category: 大学生活 (Đời sống đại học)
# INSERT INTO category (id, created_time, modified_time, category_name) VALUES (7, NOW(), NULL, '大学生活 (Đời sống đại học)');
# -- Topic: クラブ・サークル
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (20, NOW(), NULL, 'クラブ・サークル', 'サークル', 'クラブ・サークル', 'サークル', 'ACTIVE', 'N2', 20.0, NULL, 1, 7);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (47, NOW(), NULL, '大学のクラブに参加する前に、どのように情報を集めましたか。あなたの経験を話してください。', 'だいがくのクラブにさんかするまえに、どのようにじょうほうをあつめましたか。あなたのけいけんをはなしてください。', 'Trước khi tham gia câu lạc bộ ở trường đại học, bạn đã thu thập thông tin bằng cách nào? Hãy kể về kinh nghiệm của mình.', 'Trước khi tham gia câu lạc bộ ở trường đại học, bạn đã thu thập thông tin bằng cách nào? Hãy kể về kinh nghiệm của mình.', 1.0, 'PUBLISHED', NULL, 20, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (84, NOW(), NULL, '情報: Thông tin', '情報: Information');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (85, NOW(), NULL, '集める: Thu thập', '集める: Gather');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (37, NOW(), NULL, '〜前に (Trước khi...)', '〜前に (Before...)', 'Chỉ hành động diễn ra trước một việc.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (48, NOW(), NULL, '今参加しているクラブやサークルについて紹介してください。', 'いまさんかしているクラブやサークルについてしょうかいしてください。', 'Hãy giới thiệu về câu lạc bộ hoặc đội nhóm bạn đang tham gia hiện tại.', 'Hãy giới thiệu về câu lạc bộ hoặc đội nhóm bạn đang tham gia hiện tại.', 2.0, 'PUBLISHED', NULL, 20, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (86, NOW(), NULL, 'サークル: Câu lạc bộ', 'サークル: Circle');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (49, NOW(), NULL, 'クラブ活動を通して得たことは何ですか。', 'クラブかつどうをとおしてえたことはなんですか。', 'Điều bạn nhận được nhiều nhất thông qua các hoạt động câu lạc bộ là gì?', 'Điều bạn nhận được nhiều nhất thông qua các hoạt động câu lạc bộ là gì?', 3.0, 'PUBLISHED', NULL, 20, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (87, NOW(), NULL, '得る: Đạt được', '得る: Obtain');
# -- Topic: 大学の思い出
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (21, NOW(), NULL, '大学の思い出', '大学の思い出', '大学の思い出', '大学の思い出', 'ACTIVE', 'N2', 21.0, NULL, 1, 7);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (50, NOW(), NULL, '大学生活で一番思い出に残っている出来事について話してください。', 'だいがくせいかつでいちばんおもいでにのこっているできごとについてはなしてください。', 'Hãy kể về sự việc để lại nhiều kỷ niệm đáng nhớ nhất trong cuộc sống đại học của bạn.', 'Hãy kể về sự việc để lại nhiều kỷ niệm đáng nhớ nhất trong cuộc sống đại học của bạn.', 1.0, 'PUBLISHED', NULL, 21, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (88, NOW(), NULL, '思い出: Kỷ niệm', '思い出: Memory');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (89, NOW(), NULL, '出来事: Sự kiện', '出来事: Event');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (38, NOW(), NULL, '〜に残る (Đọng lại...)', '〜に残る (Remain...)', 'Lưu giữ trạng thái ở một vị trí.');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (51, NOW(), NULL, '忘れられない授業やイベントについて話してください。', 'わすれられないじゅぎょうやイベントについてはなしてください。', 'Hãy chia sẻ về một tiết học hoặc sự kiện không thể nào quên đối với bạn.', 'Hãy chia sẻ về một tiết học hoặc sự kiện không thể nào quên đối với bạn.', 2.0, 'PUBLISHED', NULL, 21, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (90, NOW(), NULL, '忘れられない: Không thể quên', '忘れられない: Unforgettable');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (91, NOW(), NULL, '授業: Tiết học', '授業: Class');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (39, NOW(), NULL, '〜られない (Không thể...)', '〜られない (Cannot...)', 'Thể khả năng phủ định.');
# -- Topic: 学生生活
# INSERT INTO topics (id, created_time, modified_time, japanese_name, japanese_description, japanese_name_markup, japanese_description_markup, status, jlpt_level, order_index, cover_image_file_id, user_id, category_id) VALUES (22, NOW(), NULL, '学生生活', '学生生活', '学生生活', '学生生活', 'ACTIVE', 'N2', 22.0, NULL, 1, 7);
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (52, NOW(), NULL, '大学で友達を作るために大切なことは何だと思いますか。', 'だいがくでともだちをつくるためにたいせつなことはなんだとおもいますか。', 'Bạn nghĩ điều gì là quan trọng để kết bạn khi học đại học?', 'Bạn nghĩ điều gì là quan trọng để kết bạn khi học đại học?', 1.0, 'PUBLISHED', NULL, 22, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (92, NOW(), NULL, '作る: Kết giao', '作る: Make');
# INSERT INTO questions (id, created_time, modified_time, title, title_markup, description, description_markup, order_index, status, question_audio_file_id, topic_id, user_id) VALUES (53, NOW(), NULL, 'あなたの大学に新入生が入学します。大学生活を楽しむためのアドバイスをしてください。', 'あなたのだいがくにしんにゅうせいがにゅうがくします。だいがくせいかつをたのしむためのアドバイスをしてください。', 'Có tân sinh viên chuẩn bị nhập học vào trường đại học của bạn. Hãy đưa ra lời khuyên để họ có thể tận hưởng cuộc sống đại học.', 'Có tân sinh viên chuẩn bị nhập học vào trường đại học của bạn. Hãy đưa ra lời khuyên để họ có thể tận hưởng cuộc sống đại học.', 2.0, 'PUBLISHED', NULL, 22, 1);
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (93, NOW(), NULL, '新入生: Tân sinh viên', '新入生: Freshman');
# INSERT INTO vocabularies (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text) VALUES (94, NOW(), NULL, 'アドバイス: Lời khuyên', 'アドバイス: Advice');
# INSERT INTO grammars (id, created_time, modified_time, vietnamese_meaning_text, english_meaning_text, explanation) VALUES (40, NOW(), NULL, '〜ための (Nhằm phục vụ...)', '〜ための (For...)', 'Bổ nghĩa cho danh từ chỉ mục đích.');
#
# -- Insert relationships between Questions and Vocabularies
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (1, 1);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (1, 2);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (2, 3);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (2, 4);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (3, 5);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (3, 6);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (4, 7);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (4, 8);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (5, 9);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (5, 10);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (6, 11);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (6, 12);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (7, 13);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (7, 14);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (8, 15);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (8, 16);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (9, 17);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (9, 18);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (10, 19);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (10, 20);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (11, 21);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (11, 22);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (12, 23);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (12, 24);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (13, 25);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (13, 26);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (14, 27);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (14, 28);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (15, 29);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (15, 30);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (16, 31);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (16, 32);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (17, 33);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (17, 34);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (18, 35);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (18, 36);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (19, 37);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (19, 38);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (20, 39);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (20, 40);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (21, 41);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (21, 42);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (22, 43);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (22, 44);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (23, 45);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (23, 43);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (24, 46);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (24, 47);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (25, 48);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (25, 49);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (26, 50);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (26, 51);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (27, 52);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (27, 28);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (28, 53);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (28, 54);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (29, 55);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (29, 56);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (30, 57);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (30, 49);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (31, 58);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (31, 39);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (32, 59);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (32, 60);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (33, 61);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (33, 62);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (34, 63);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (34, 33);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (35, 57);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (35, 64);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (36, 51);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (36, 49);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (37, 65);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (37, 66);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (38, 67);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (38, 68);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (39, 69);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (39, 70);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (40, 71);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (40, 72);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (41, 73);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (41, 74);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (42, 75);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (42, 76);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (43, 77);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (43, 78);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (44, 79);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (44, 80);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (45, 81);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (45, 82);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (46, 80);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (46, 83);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (47, 84);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (47, 85);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (48, 86);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (48, 76);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (49, 74);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (49, 87);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (50, 88);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (50, 89);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (51, 90);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (51, 91);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (52, 92);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (52, 47);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (53, 93);
# INSERT INTO questions_vocabularies (question_id, vocabulary_id) VALUES (53, 94);
#
# -- Insert relationships between Questions and Grammars
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (1, 1);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (2, 2);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (3, 3);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (4, 4);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (5, 5);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (6, 6);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (7, 7);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (8, 8);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (9, 9);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (10, 10);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (11, 11);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (12, 12);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (2, 13);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (13, 14);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (14, 15);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (13, 16);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (15, 17);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (16, 18);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (17, 19);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (18, 20);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (19, 21);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (20, 22);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (7, 23);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (21, 24);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (22, 25);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (23, 26);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (24, 27);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (25, 28);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (26, 29);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (27, 30);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (28, 31);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (5, 32);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (4, 33);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (1, 34);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (29, 35);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (22, 36);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (30, 37);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (31, 38);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (32, 39);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (26, 40);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (33, 41);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (9, 42);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (34, 43);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (35, 44);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (36, 45);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (14, 46);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (37, 47);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (6, 48);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (34, 49);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (38, 50);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (39, 51);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (5, 52);
# INSERT INTO questions_grammars (grammar_id, question_id) VALUES (40, 53);
