INSERT INTO chests (id, created_time, modified_time, title, description, point)
VALUES
    (1, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (2, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài luyện nói', 10.0),
    (3, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (4, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (5, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (6, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (7, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (8, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (9, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (10, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (11, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (12, NOW(), NULL, 'Rương Vàng Lớn', 'Phần thưởng đặc biệt hoàn thành toàn bộ Topic 1', 50.0),
    (13, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (14, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (15, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (16, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (17, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (18, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (19, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (20, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (21, NOW(), NULL, 'Rương Vàng Lớn', 'Phần thưởng đặc biệt hoàn thành toàn bộ Topic 2', 50.0),
    (22, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (23, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (24, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài luyện nói', 10.0),
    (25, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (26, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (27, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (28, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài luyện nói', 10.0),
    (29, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (30, NOW(), NULL, 'Rương Vàng Lớn', 'Phần thưởng đặc biệt hoàn thành toàn bộ Topic 3', 50.0),
    (31, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (32, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (33, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài luyện nói', 10.0),
    (34, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (35, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (36, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (37, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài luyện nói', 10.0),
    (38, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (39, NOW(), NULL, 'Rương Vàng Lớn', 'Phần thưởng đặc biệt hoàn thành toàn bộ Topic 4', 50.0),
    (40, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (41, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (42, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài luyện nói', 10.0),
    (43, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (44, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (45, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (46, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài luyện nói', 10.0),
    (47, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (48, NOW(), NULL, 'Rương Vàng Lớn', 'Phần thưởng đặc biệt hoàn thành toàn bộ Topic 5', 50.0),
    (49, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (50, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (51, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài luyện nói', 10.0),
    (52, NOW(), NULL, 'Rương Vàng', 'Phần thưởng hoàn thành', 25.0),
    (53, NOW(), NULL, 'Rương Nhỏ', 'Phần thưởng sau bài từ vựng', 10.0),
    (54, NOW(), NULL, 'Rương Vàng Lớn', 'Phần thưởng đặc biệt hoàn thành toàn bộ Topic 6', 50.0);