package org.naho.point.type;

public enum PointTransactionType {
    LEARNING_PATH_NODE_COMPLETION,
    CAN_DO_COMPLETION,
    LESSON_COMPLETION,
    TOPIC_COMPLETION,
    BOOK_COMPLETION,
    DAILY_LOGIN_REWARD,
    DAILY_MISSION_REWARD,
    RETAKE,
    STREAK_BONUS,
    ACHIEVEMENT_REWARD,
    PENALTY
}
